Update

diff --git a/entrypoint.patch b/entrypoint.patch
--- a/entrypoint.patch
+++ b/entrypoint.patch
@@ -1,5 +1,5 @@
---- docker-entrypoint.sh	2018-04-12 22:34:25.421405943 -0400
-+++ entrypoint_modif	2018-04-12 22:34:15.029459830 -0400
+--- docker-entrypoint.sh	2018-04-12 22:58:54.965384278 -0400
++++ entrypoint_modif	2018-04-12 22:58:48.957421417 -0400
 @@ -40,6 +40,11 @@
  	unset "$fileVar"
  }
@@ -50,7 +50,7 @@
  			fi
  
  			echo 'FLUSH PRIVILEGES ;' | "${mysql[@]}"
-@@ -185,6 +186,19 @@
+@@ -185,6 +186,33 @@
  		echo
  		echo 'MySQL init process done. Ready for start up.'
  		echo
@@ -61,7 +61,21 @@
 +		"$@" --skip-networking --socket="${SOCKET}" &
 +		pid="$!"
 +
-+		mysql -hlocalhost -uroot -p"${MYSQL_ROOT_PASSWORD}" -e "ALTER USER '$MYSQL_USER'@'%' IDENTIFIED BY '$MYSQL_PASSWORD';"
++		mysql=( mysql --protocol=socket -uroot -hlocalhost --socket="${SOCKET}" )
++
++		for i in {30..0}; do
++			if echo 'SELECT 1' | "${mysql[@]}" &> /dev/null; then
++				break
++			fi
++			echo 'MySQL init process in progress...'
++			sleep 1
++		done
++		if [ "$i" = 0 ]; then
++			echo >&2 'MySQL init process failed.'
++			exit 1
++		fi
++
++#		mysql -hlocalhost -uroot -p"${MYSQL_ROOT_PASSWORD}" -e "ALTER USER '$MYSQL_USER'@'%' IDENTIFIED BY '$MYSQL_PASSWORD';"
 +	
 +		if ! kill -s TERM "$pid" || ! wait "$pid"; then
 +			echo >&2 'MySQL init process failed.'
diff --git a/entrypoint_modif b/entrypoint_modif
--- a/entrypoint_modif
+++ b/entrypoint_modif
@@ -193,7 +193,21 @@ if [ "$1" = 'mysqld' -a -z "$wantHelp" ]; then
 		"$@" --skip-networking --socket="${SOCKET}" &
 		pid="$!"
 
-		mysql -hlocalhost -uroot -p"${MYSQL_ROOT_PASSWORD}" -e "ALTER USER '$MYSQL_USER'@'%' IDENTIFIED BY '$MYSQL_PASSWORD';"
+		mysql=( mysql --protocol=socket -uroot -hlocalhost --socket="${SOCKET}" )
+
+		for i in {30..0}; do
+			if echo 'SELECT 1' | "${mysql[@]}" &> /dev/null; then
+				break
+			fi
+			echo 'MySQL init process in progress...'
+			sleep 1
+		done
+		if [ "$i" = 0 ]; then
+			echo >&2 'MySQL init process failed.'
+			exit 1
+		fi
+
+#		mysql -hlocalhost -uroot -p"${MYSQL_ROOT_PASSWORD}" -e "ALTER USER '$MYSQL_USER'@'%' IDENTIFIED BY '$MYSQL_PASSWORD';"
 	
 		if ! kill -s TERM "$pid" || ! wait "$pid"; then
 			echo >&2 'MySQL init process failed.'
